name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-13, windows-2022 ]
        java: [ 17, 20 ]
        gradle: [ 8.3, nightly ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          gradle-version: ${{ matrix.gradle }}
      - name: Build
        run: gradle build --stacktrace --warning-mode fail

  docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm i
        working-directory: ./docs
      - run: npm run build
        working-directory: ./docs